version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: projet_cloud
      POSTGRES_USER: mon_utilisateur
      POSTGRES_PASSWORD: mon_mot_de_passe
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  tomcat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tomcat-server
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=projet_cloud
      - DB_USER=mon_utilisateur
      - DB_PASSWORD=mon_mot_de_passe

volumes:
  postgres-data:
    driver: local
