version: '3.8'

services:
  tomcat:
    build: .
    container_name: tomcat-servlet
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres:5432/projet_cloud
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres

  postgres:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_DB: projet_cloud
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
